# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonFrame = QtWidgets.QFrame(Form)
        self.buttonFrame.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.buttonFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelingButton = QtWidgets.QRadioButton(self.buttonFrame)
        self.labelingButton.setObjectName("labelingButton")
        self.optionButtons = QtWidgets.QButtonGroup(Form)
        self.optionButtons.setObjectName("optionButtons")
        self.optionButtons.addButton(self.labelingButton)
        self.verticalLayout_3.addWidget(self.labelingButton)
        self.viewerButton = QtWidgets.QRadioButton(self.buttonFrame)
        self.viewerButton.setObjectName("viewerButton")
        self.optionButtons.addButton(self.viewerButton)
        self.verticalLayout_3.addWidget(self.viewerButton)
        self.verticalLayout.addWidget(self.buttonFrame)
        self.confirmFrame = QtWidgets.QFrame(Form)
        self.confirmFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.confirmFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.confirmFrame.setObjectName("confirmFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.confirmFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.confirmFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.confirmFrame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelingButton.setText(_translate("Form", "Segmentation Labeling"))
        self.viewerButton.setText(_translate("Form", "Segmentation Viewer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
